config/routes.rb
Rails.application.routes.draw do

  root 'frontpage#index'

  #resources :joblist
  get 'joblist' => 'joblist#index'
  post 'joblist' => 'joblist#create'
  put 'joblisting/:id' => 'joblist#update'

  resources :joblisting, only: %w(new edit show destroy), controller: "joblist"

  # clearance gem defines its own paths for user handling
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joblisting.rb
class Joblisting < ApplicationRecord
  belongs_to :user
  validates_presence_of  :title, uniqueness: true
  validates_presence_of  :description
  validates_presence_of  :user
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :joblistings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def index
  	if !current_user.nil?
  		@jobs = current_user.joblistings.all.order(:id)
  	end
  end
end

app/controllers/joblist_controller.rb
class JoblistController < ApplicationController

  def index
    @jobs = Joblisting.all.order(:id)
  end

  def show
    @job = Joblisting.find(params[:id])
  end

  def new
    if !current_user.nil?
      @job = current_user.joblistings.build()
    else
      redirect_to joblist_path, notice: "Forbidden. Log in before attempting."
    end
  end

  def create
    if !current_user.nil?
      @job = current_user.joblistings.build(joblisting_params)

      if @job.save
        redirect_to joblist_path(@job), notice: 'Created job listing.'
      else
        @errors = @job.errors.full_messages
        render :new
      end
    else
      redirect_to joblist_path, notice: "Forbidden. Log in before attempting."
    end
  end

  def edit
    if !current_user.nil?
      @job = Joblisting.find(params[:id])

      if @job.user != current_user
        redirect_to joblist_path, notice: 'Forbidden.'
      end
    else
      redirect_to joblist_path, notice: 'Forbidden. Log in before attempting.'
    end
  end

  def update
    if !current_user.nil?
      @job = Joblisting.find(params[:id])

      if @job.user == current_user
        if @job.update_attributes(joblisting_params)
          redirect_to joblist_path(@job), notice: 'Updated job listing.'
        else
          @errors = @job.errors.full_messages
          render :edit
        end
      end
    else
      redirect_to joblist_path, notice: "Forbidden. Log in before attempting."
    end
  end

  def destroy
    if !current_user.nil?
      job = Joblisting.find(params[:id])

      if job.user == current_user
        job.destroy
        redirect_to joblist_path, notice: "Deleted job listing: #{job.title}"
      else
        redirect_to joblist_path, notice: "Forbidden."
      end
    else
      redirect_to joblist_path, notice: "Forbidden. Log in before attempting."
    end
  end

  private
  # validating a form, used for creating new job listings
  def joblisting_params
    params.require(:joblisting).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title, page_title.to_s)
  end
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/views/frontpage/index.html.erb
<% title("Jobapp - Index") %>

<h1 class="frontpage-header">Front page</h1>

<% if @current_user != nil %>
  <h2>Your job listings</h2>

  <% @jobs.each do |joblisting| %>
      <div class="job">
        <h3><%= link_to(joblisting.title, joblisting_path(joblisting))%></h3>
        <p><%= joblisting.description %></p>

        <% if signed_in? %>
          <% if current_user == joblisting.user %>
            <div class="joblisting-actions">
              <%= link_to("Update", edit_joblisting_path(joblisting)) %> | <%= link_to("Delete", joblisting_path(joblisting), data: {
                confirm: "Are you sure you want to delete job listing with title \"#{joblisting.title}\"?"
            }, method: :delete) %>
            </div>
          <% end %>
        <% end %>
      </div>
  <% end %>
<% end %>

app/views/joblist/edit.html.erb
<% title("Jobapp - Update job listing") %>

<h1>Edit joblisting</h1>

<% if @errors.present? %>
    <div class="errors">
      <ul>
        <% @errors.each do |error| %>
            <li><%= error %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @job, url: joblisting_path(@job), html: { method: :put } do |form| %>
    <table>
      <tr>
        <div class="form-group">
          <td><%= form.label :title %></td>
          <td><%= form.text_field :title %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <td><%= form.label :description %></td>
          <td><%= form.text_area :description %></td>
        </div>
      </tr>
      <tr>
        <td colspan="2">
          <div class="actions">
            <%= form.submit %>
          </div>
        </td>
      </tr>
    </table>
<% end %>
<br/>
<%= link_to('Back to list', joblist_path) %>

app/views/joblist/index.html.erb
<% title('Jobapp - All job listings') -%>

<h1>Job listings</h1>

<div>
  <%= link_to("Create new job listing", new_joblisting_path) %>
</div>

<% @jobs.each do |joblisting| %>
  <div class="job">
    <h3><%= link_to(joblisting.title, joblisting_path(joblisting))%></h3>
    <p><%= joblisting.description %></p>

    <% if signed_in? %>
      <% if current_user == joblisting.user %>
        <div class="joblisting-actions">
          <%= link_to("Update", edit_joblisting_path(joblisting)) %> | <%= link_to("Delete", joblisting_path(joblisting), data: {
            confirm: "Are you sure you want to delete job listing with title \"#{joblisting.title}\"?"
        }, method: :delete) %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/joblist/new.html.erb
<% title("Jobapp - New job listing") %>

<h1>Create new joblisting</h1>

<% if @errors.present? %>
    <div class="errors">
      <% @errors.each do |error| %>
        <p><%= error %>.</p>
      <% end %>
    </div>
<% end %>

<%= form_for(@job, url: joblist_path(@user), html: { method: :post }) do |form| %>
    <table>
      <tr>
        <div class="form-group">
          <td><%= form.label :title %></td>
          <td><%= form.text_field :title %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <td><%= form.label :description %></td>
          <td><%= form.text_area :description %></td>
        </div>
      </tr>
      <tr>
        <td colspan="2">
          <div class="actions">
            <%= form.submit %>
          </div>
        </td>
      </tr>
    </table>
<% end %>
<br/>
<%= link_to('Back to list', joblist_path) %>

app/views/joblist/show.html.erb
<% title('Jobapp - ' + @job.title) %>

<h1><%= @job.title %></h1>

<h3>Description:</h3>
<p><%= @job.description %></p>

<% if signed_in? %>
  <% if current_user == @job.user %>
    <div class="joblisting-actions">
      <%= link_to("Update", edit_joblisting_path(@job)) %> | <%= link_to("Delete", joblisting_path(@job), data: {
          confirm: "Are you sure you want to delete job listing with title \"#{@job.title}\"?"
      }, method: :delete) %>
    </div>
  <% end %>
<% end %>

<%= link_to("Back", joblist_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= if content_for?(:title)
             yield(:title) else 'Jobapp - default' end %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload') %>
    <%= javascript_include_tag('application', 'data-turbolinks-track': 'reload') %>
  </head>

  <body>
    <header class="container">
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to('Sign out', sign_out_path, method: :delete) %>
      <% else %>
        <%= link_to('Sign in', sign_in_path) %>
      <% end %>
    </header>

    <div id="border"></div>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </section>

    <footer class="container">
      <%= link_to('See your job listings', root_path) %> | <%= link_to('See all job listings', joblist_path) %>
    </footer>
  </body>
</html>